# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', 'run_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('avg_rate', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('apply_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(default='안녕하세요 :D 지원해주셔서 감사합니다.')),
                ('link_url', models.URLField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('has_image_form', models.BooleanField(default=True)),
                ('has_attached_file_form', models.BooleanField(default=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('example_answer', models.TextField()),
                ('priority', models.IntegerField()),
                ('type', models.CharField(choices=[('S', 'Short'), ('L', 'Long')], max_length=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Application')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Application'),
        ),
        migrations.AddField(
            model_name='answer',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Applicant'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Question'),
        ),
    ]
